feature - Typography tokens
ZanichelliEditore/design-tokens pull request #7
Opened 2021-06-01 13:33 UTC by DarioSacco

Add typography tokens and classes.

[Abstract reference](https://share.goabstract.com/02b2e8e6-119f-4c15-bc59-cb31f70e94a3?collectionLayerId=6efdba15-3593-48b6-81ec-c476047ee440&mode=design)

2021-06-03 13:57 UTC, nitroin requested changes

2021-06-03 13:57 UTC, nitroin commented on src/modules/typography.scss
> +  --font-size-1: 12px;
Should we use `rem`?

2021-06-03 13:57 UTC, nitroin commented on src/modules/typography.scss
> +}
Those tokens should be co-located with the typography component already available on albe?

2021-06-09 14:30 UTC, nitroin approved these changes

2021-06-10 08:01 UTC, manuelzane approved these changes

2021-06-10 12:38 UTC, merged